### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by JamesSingleton** [JamesSingleton/react-building-modules#1]
Setup CircleCI to actually do a proper build instead of just echoing `A first hello`. I am not too familiar with CircleCI, so any help would be greatly appreciated.

**Comment by bbeesley** [comment]
Added circle ci config to check it builds properly (see PR) but both on my machine and on circle the build is currently broken (https://circleci.com/gh/bbeesley/react-building-blocks/2).

Looks like the issue is with this line `import Button from './Button';` in `src/components/Button/index.js`. You're importing from a directory called `Button` but the directory is actually called `button`. Maybe you're not using a case sensitive filesystem on your machine?

**Comment by bbeesley** [comment]
OK, pushed a fix for that issue as well on the same branch. Build is passing now: https://circleci.com/gh/bbeesley/react-building-blocks/3

**Comment by JamesSingleton** [comment]
@bbeesley thought I would continue the conversation here. I added at least one test for `Button` for now just to get things going in the right direction. Let me know what I need to do when you get a chance.

**Comment by JamesSingleton** [comment]
@bbeesley I have made it so all components have 100% code coverage now for the ones that I currently have.

**Comment by JamesSingleton** [comment]
I believe I have finished setting this up.
